### ISSUE TITLE
Status of compare_t

### ISSUE THREAD

**Issue by pveber** [janestreet/ppx_compare#1]
As I understand from the doc, `compare_t` is generated as an alias for `compare`, but not exported. I am guessing `compare_t` is kept for compatibility with previous versions of `ppx_compare`, but I find it strange not to export it in the signature. For old code this means one has to add the function manually, and for newer code, this makes the compiler warn that `compare_t` is not used (warning 32). Maybe I'm missing something here, but wouldn't it be more coherent to export this alias as well?

**Comment by v-gb** [comment]
This problem was solved by removing `compare_t` in November 2016.

**Comment by pveber** [comment]
Indeed `:o)`. Thanks!
