### ISSUE TITLE
Cannot run tests (Error: No rule found for test/comparelib_test__Check_optims.o)

### ISSUE THREAD

**Issue by pukkamustard** [janestreet/ppx_compare#10]
While running tests I get following error:

```
dune runtest
File "test/dune", line 6, characters 0-169:
6 | (alias (name runtest) (deps comparelib_test__Check_optims.o)
7 |  (action
8 |   (bash
9 |    "objdump -t comparelib_test__Check_optims.o | { ! grep -Eq 'caml_(compare|equal)'; }")))
Error: No rule found for test/comparelib_test__Check_optims.o
Done: 0/0 (jobs: 0)
```

A quick online search revealed that this might have been observed in the Arch Linux packaged version of ppx_compare as well: https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=ocaml-ppx_compare#n25

Can anybody else reproduce this error? Pointers on how to fix this?

Thanks!

**Comment by aalekseyev** [comment]
I believe this should be fixed in 04acd66.
