### ISSUE TITLE
Annotating inequality

### ISSUE THREAD

**Issue by cmxog** [janestreet/ppx_compare#11]
Hey, thanks for this great library! I am running into a case of deriving `equal` for types that contain functions. Obviously, such types are incomparable and ppx_compare mentions that:

```ocaml
type typ = | A of (int -> int) | B [@@deriving equal];;
```

results in

```
Error: ppx_compare: Functions can not be compared.
```

Fair enough. However, the only way to work around this I found is applying `@equal.ignore` annotation to `(int -> int)`. That being said, I don't think the code that it generates suits the purpose:

```ocaml
utop # type typ = | A of (int -> int [@equal.ignore]) | B [@@deriving equal];;
type typ = A of (int -> int) | B   
val equal_typ : typ -> typ -> bool = <fun>  

utop # equal_typ (A (fun x -> x)) (A (fun x -> x + 1));;     
- : bool = true      
```

It's rather not correct to say that these two functions are in fact equal. What I am looking for is a way to annotate that the type is always going to be unequal (perhaps, can't be applied to `compare` as there is no ordering to be derived for that):

```ocaml
utop # type typ = | A of (int -> int [@equal.never]) | B [@@deriving equal];;
...

utop # equal_typ (A (fun x -> x)) (A (fun x -> x);;
- : bool = false
```

This makes sense to me as I can still derive equality function for `typ` and it will simply indicate the never-equality of the `A`-constructed type.

I think `@equal.never` annotation would be an approach that can be successfully used for functions and other types alike where they should never equate.

I don't know how busy you are and how much interest is there to spend time implementing this feature. I have never written a ppx library but I am happy to try and send a PR to implement this if you don't have the time for it now.

Any thoughts?

**Comment by v-gb** [comment]
A well behaved equality function is reflexive, meaning `equal x x` will be true for all `x` of the right type.

You're of course free to break that property if it doesn't matter in your case, but we don't want `ppx_compare` to encourage this by making it easier.

If you want to tweak the behavior of equality, this can be done the same way as with all such preprocessors, by making a type alias with a custom behavior:

```ocaml
type z = int -> int
let equal_z : z -> z -> bool = fun _ _ -> false (* although, at a minimum, using physical equality would be better *)

type typ = | A of z | B [@@deriving equal]
```

At most, what we could do is make it possible to override equality behavior inline, instead of going through a type alias.

**Comment by cmxog** [comment]
Thanks for the feedback!

**Comment by cmxog** [comment]
I would note here that overriding the behavior inline is important. Considering the following (modelled after a real case that I have):

```
type value = 
| Int of int
| Fun of fn
and fn = value -> value
[@@deriving equal]
```

The problem here (as I see it, unless I miss something) that I can't define `equal_fn` separately as `fn` and `value` are mutually recursive. Do you think there's any workaround for this or this indeed requires inline equality behavior  overriding change?

**Comment by v-gb** [comment]
Yeah, recursive definitions are definitely more annoying.

It's still possible to do something like this:
```ocaml
type 'a not_equal = 'a
let equal_not_equal _ _ _ = false

type value = 
| Int of int
| Fun of fn not_equal
and fn = value -> value [@equal.ignore]
[@@deriving equal]
```

or in more complicated cases:

```ocaml
type value0 = 
| Int of int
| Fun of fn
and fn = value0 -> value0
let equal_fn _ _ = false

type value = value0 =
| Int of int
| Fun of fn
[@@deriving equal]
```

but it's definitely harder than it seems like it should.

**Comment by v-gb** [comment]
If you want to try and implement `type t = (int -> int [@equal.override fun _ _ -> false])`, it's probably not too hard, although there's a bit of a learning curve with ppx stuff.
