### ISSUE TITLE
Unbound value compare_option

### ISSUE THREAD

**Issue by mimoo** [janestreet/ppx_compare#12]
I'm trying to make a record comparable:

```ocaml
type 'field t =
  { system : 'field Constraint_system.t option
  ; input : 'field Vector.t
  ; aux : 'field Vector.t
  ; eval_constraints : bool
  ; num_inputs : int
  ; next_auxiliary : int ref
  ; has_witness : bool
  ; stack : string list
  ; handler : Request.Handler.t
  ; is_running : bool
  ; as_prover : bool ref
  ; log_constraint :
      (   ?at_label_boundary:[ `Start | `End ] * string
       -> ('field Cvar.t, 'field) Constraint.t option
       -> unit )
      option
        [@compare.ignore]
  }
[@@deriving compare]
```

but I'm getting the following error:

```
Entering directory '/Users/davidwong/Work/mina_nix'
File "src/lib/snarky/src/base/run_state.ml", line 36, characters 40-46:
36 |   { system : 'field Constraint_system.t option
                                             ^^^^^^
Error: Unbound value compare_option
```

**Comment by mimoo** [comment]
I used `open Ppx_compare_lib.Builtin` right before `t` and it works now, but that seems a bit hacky as everything is brought to scope

**Comment by v-gb** [comment]
I'll tweak the readme to say something about this, but the normal thing to do is open either `core` or `base`. `Ppx_compare_lib.Builtin` also works. I don't see what's hacky: the type option, list, ref are put in scope by the implied `open Stdlib`, so the corresponding comparisons also need to be put in scope. The `Builtin` module contains just what's necessary and no more.

**Comment by mimoo** [comment]
I guess the problem with opening is that you have no idea what you're bringing into scope (and this can change as you upgrade the dependency)

**Comment by v-gb** [comment]
In general, sure, but the modules I listed are meant to be opened. Certainly, if you look at the `Builtin` module, it contains a small set of functions that are unlikely to collide or shadow anything.
