### ISSUE TITLE
non-terminating compare derived from nonrec type

### ISSUE THREAD

**Issue by ivg** [janestreet/ppx_compare#2]
With ppx_jane.113.03 and OCaml 4.02.3, the following program:

``` ocaml
type t = int

module T = struct
  type nonrec t = t [@@deriving compare]
end 

let () =
  let _ = Unix.alarm 1 in
  print_int (T.compare 1 2)
```

Terminate with `-1` (or doesn't terminate if the alarm is not set). 

Compiled with:

```
ocamlbuild -use-ocamlfind -pkgs ppx_jane inf.native --
```

The interesting thing is that when you ask `ppx-jane` to dump the program, `ppx-jane inf.ml -o -` it will output code that terminates:

``` ocaml
type t = int
module T =
  struct
    type nonrec t = t[@@nonrec ]
    let _ = fun (_ : t)  -> ()
    let compare: t -> t -> int =
      fun a__001_  -> fun b__002_  -> compare a__001_ b__002_
    let _ = compare
    let compare_t = compare
    let _ = compare_t
  end
let () = let _ = Unix.alarm 1 in print_int (T.compare 1 2)
```

**Comment by jberdine** [comment]
FTR: I'm also hitting this.

**Comment by v-gb** [comment]
Very surprising bug report, given that we do exactly this all the time (and more complicated things like `type nonrec t = t list`), and there have been no release where this was known to be broken.

Given that the code generated by ppx_jane/ppx_compare is correct, my only guess is that you were using ppx_deriving, that ppx_deriving was the one implementing [@@deriving compare] (or perhaps both ppx_deriving and ppx_compare were implementing it), as it's possible that `ppx_deriving` didn't handle nonrec properly.

So I'm going to close this. If someone still runs into the problem, run the compiler with -dsource or -dparsetree (whichever ever one gives the ast with [@@deriving ..] expanded), so we can know for sure what ast the compiler sees.

**Comment by v-gb** [comment]
And I forgot to say: `type nonrec t = t` generates `let compare : t -> t -> int = compare` now, so that can't possibly loop. Even if we somehow generated `let rec compare = compare`, it would be rejected by the compiler.

**Comment by ivg** [comment]
It was four years ago, in before dune times, and indeed most likely the culprit was `ppx_deriving` plus configuration (all these predicates in META files) that weren't working correctly when both ppx_jane and ppx_deriving are installed in the switch. I remember I was creating an issue somewhere in core/core_kernel about this. But since many things have changed and the interaction between derivers is more reliable now.

**Comment by jberdine** [comment]
Yes, long time ago, but for the record we hit this with Infer as well in cases such as `type nonrec t = (t * bool) list [@@deriving compare]` where the generated function used `let rec` instead of `let` despite the `nonrec` flag. For archeological purposes, an instance of working around this appeared [here](https://github.com/facebook/infer/commit/6459ec4ff4383acfbeda94da450f5fc75f5187f2). At that point building was via ocamlbuild, using [`package(ppx_compare)`](https://github.com/facebook/infer/blob/6459ec4ff4383acfbeda94da450f5fc75f5187f2/infer/src/Makefile#L38).

I just checked a couple examples, and they now produce good code.
