### ISSUE TITLE
derive compare for one of several mutually recursive types

### ISSUE THREAD

**Issue by rgrig** [janestreet/ppx_compare#9]
Here's an example:
```
type t0 = ... (* some complicated type that doesn't need compare *)
type t1 = A of t0 | B of t2 and t2={a:int; b:t1 [@compare.ignore]};;
let rec compare_t2 = [%compare: t2];;
```

PROBLEM: the `rec` is required. It should not be necessary.
(Is there another way to get a compare_t2 but not compare_t1?)

**Comment by rgrig** [comment]
Oh, and it doesn't terminate with `rec`.

```
utop # #require "ppx_compare";;
utop # type t1 = A of t2 | B and t2 = {a:int; b:t1 [@compare.ignore]};;
type t1 = A of t2 | B
and t2 = { a : int; b : t1; }
utop # let compare_t2 = [%compare: t2];;
Line 1, characters 28-30:
Error: Unbound value compare_t2
Hint: Did you mean compare?
utop # let rec compare_t2 = [%compare: t2];;
val compare_t2 : t2 -> t2 -> 'a = <fun>
utop # compare_t2 {a=1;b=B} {a=1;b=B};;
```
... runs forever

**Comment by v-gb** [comment]
`let rec compare_t2 = [%compare: t2];;` expands to `let rec compare_t2 x y = compare_t2 x y`, so yeah it doesn't terminate. Why did you add `rec` in the first place? Did the compiler suggest it?

There's no mechanism to derive something for one type in a mutually recursive group but not others, in ppx_compare or other ppxes. Can't you simply do:

```ocaml
type t0 = ... (* some complicated type that doesn't need compare *)
type t1 = A of (t0 [@compare.ignore]) | B of t2 and t2={a:int; b:t1 [@compare.ignore]} [@@deriving compare];;
```

and not use `compare_t1`, or shadow it?

**Comment by rgrig** [comment]
I tried `rec` because I thought, at the time, that `[%compare: t2]` would look at the definition of `t2` to generate code.

The suggested fix does not compile (v0.14.0):
```
Error: Unbound value compare_t0
```

**Comment by jberdine** [comment]
`[@compare.ignore]` is not supported on individual constructors. It works if you put the `t0` in an inline record:
```ocaml
type t0 = unit -> unit (* some complicated type that doesn't need compare *)

type t1 = A of {c: t0 [@compare.ignore]} | B of t2

and t2 = {a: int; b: t1 [@compare.ignore]} [@@deriving_inline compare]

let _ = fun (_ : t1) -> ()
let _ = fun (_ : t2) -> ()

let rec compare_t1 =
  (fun a__001_ ->
     fun b__002_ ->
       if Ppx_compare_lib.phys_equal a__001_ b__002_
       then 0
       else
         (match (a__001_, b__002_) with
          | (A _a__003_, A _b__004_) -> 0
          | (A _, _) -> (-1)
          | (_, A _) -> 1
          | (B _a__005_, B _b__006_) -> compare_t2 _a__005_ _b__006_) :
  t1 -> t1 -> int)
and compare_t2 =
  (fun a__007_ ->
     fun b__008_ ->
       if Ppx_compare_lib.phys_equal a__007_ b__008_
       then 0
       else compare_int a__007_.a b__008_.a : t2 -> t2 -> int)

let _ = compare_t1
and _ = compare_t2

[@@@end]
```

**Comment by v-gb** [comment]
Yeah `[@compare.ignore]` doesn't work on constructors. I intended to ignore the argument of the constructor. I added the pair of paren to my comment above to make it work.

**Comment by rgrig** [comment]
Thanks both! Those solutions work. In the [commit that triggered this](https://github.com/facebook/infer/commit/c829db496429868f55f977477d513cd36098f359#diff-608d9f2609b7f44d1cef197efe6a82ccad1c3da16398f250390e93bf46ac70bfR51) I think @jvillard suggested just adding `[@@deriving compare]` to `t0`. All three workarounds involve about as much pain as each-other (in the real code there'd be quite a few places where you'd need to add `compare.ignore`). But it's not that bad.

I guess whether you want to close this or not depends on whether you think it happens often enough that you want to derive compare for a proper subset of mutually recursive types. My guess is it probably doesn't happen that often.

Thanks again.

**Comment by v-gb** [comment]
Cool. I'm going to close this then. The request is reasonable, but since it's the first time I've seen it and that the way to address this is not clear (something specific to ppx_compare vs a more general mechanism to derive things for a subset of the type names), I'd rather wait until this comes up again before trying to support it.
